### ISSUE TITLE
Datasets labels

### ISSUE THREAD

**Issue by vanhoan310** [RubD/spatial-datasets#1]
Dear developers! 
Are labels provided in the datasets taken from the Giotto clustering or they are the ground truth labels from the original publication?
e.g. https://github.com/RubD/spatial-datasets/blob/master/data/2019_seqfish_plus_olfactory_bulb/cell_locations/OB_centroids_annot.txt

Thanks!

**Comment by RubD** [comment]
Hi @vanhoan310 
We created and annotated our own clusters and thus did not use the cell type labels from the original papers. Depending on how you set your parameters and the questions that you might have, you will likely end up with different clusters. And thus ground truth labels are hard to agree on.
Best

**Comment by vanhoan310** [comment]
Thanks!
